name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    steps:

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH host to known_hosts
        run: |
          ssh-keyscan -H 13.233.146.20 >> ~/.ssh/known_hosts

      - name: SSH & Deploy
        run: |
            ssh -i ~/.ssh/id_rsa ubuntu@13.233.146.20 << 'EOF'
            cd monorepo-aws/
            git pull
            # Install pnpm if not present
            if ! command -v pnpm &> /dev/null; then
                npm install -g pnpm
            fi
            pnpm install
            pnpm run build
            pnpm restart fe-server
            pnpm restart http-server
            pnpm restart ws-server
            EOF